services:
  mariadb:
    image: mariadb:11
    container_name: keycloak-db
    environment:
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloak
      MARIADB_ROOT_PASSWORD: keycloak
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - keycloak-net
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      KC_DB: mariadb
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - keycloak-net
    command: start-dev

volumes:
  mariadb_data:

networks:
  keycloak-net: