import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { SwissNumberFormatPipe } from '../../../pipes/swiss-number-format/swiss-number-format.pipe';
import { ProductListItemComponent } from '../product-list-item/product-list-item.component';
import { Bike } from '../../../models/bike.model';

@Component({
    selector: 'app-product-list',
    imports: [CommonModule, RouterModule, ProductListItemComponent],
    templateUrl: './product-list.component.html',
    styleUrl: './product-list.component.css'
})
export class ProductListComponent {
  protected mockProducts: Bike[] = [
    {
      id: 1,
      name: 'MT-07',
      make: 'Yamaha',
      price: 5200,
      year: 2017,
      kilometers: 18000,
      horsepower: 74,
      condition: 'Gebraucht',
    },
    {
      id: 2,
      name: 'CBR500R',
      make: 'Honda',
      price: 4300,
      year: 2014,
      kilometers: 24000,
      horsepower: 47,
      condition: 'Gebraucht',
    },
    {
      id: 3,
      name: 'Ninja 650',
      make: 'Kawasaki',
      price: 5800,
      year: 2018,
      kilometers: 15000,
      horsepower: 67,
      condition: 'Gebraucht',
    },
    {
      id: 4,
      name: 'Iron 883',
      make: 'Harley-Davidson',
      price: 6400,
      year: 2012,
      kilometers: 32000,
      horsepower: 50,
      condition: 'Gebraucht',
    },
    {
      id: 5,
      name: 'SV650',
      make: 'Suzuki',
      price: 4700,
      year: 2016,
      kilometers: 21000,
      horsepower: 75,
      condition: 'Gebraucht',
    },
    {
      id: 6,
      name: 'Duke 390',
      make: 'KTM',
      price: 5100,
      year: 2020,
      kilometers: 8000,
      horsepower: 44,
      condition: 'Neu',
    },
    {
      id: 7,
      name: 'R1200GS',
      make: 'BMW',
      price: 9800,
      year: 2015,
      kilometers: 29000,
      horsepower: 125,
      condition: 'Gebraucht',
    },
    {
      id: 8,
      name: 'Monster 796',
      make: 'Ducati',
      price: 7300,
      year: 2013,
      kilometers: 27000,
      horsepower: 87,
      condition: 'Gebraucht',
    },
    {
      id: 9,
      name: 'Street Triple R',
      make: 'Triumph',
      price: 7900,
      year: 2019,
      kilometers: 12000,
      horsepower: 116,
      condition: 'Gebraucht',
    },
    {
      id: 10,
      name: 'V Star 950',
      make: 'Yamaha',
      price: 4100,
      year: 2011,
      kilometers: 34000,
      horsepower: 53,
      condition: 'Neu',
    },
    {
      id: 11,
      name: 'Interceptor 650',
      make: 'Royal Enfield',
      price: 6000,
      year: 2021,
      kilometers: 6000,
      horsepower: 47,
      condition: 'Neu',
    },
    {
      id: 12,
      name: 'Vulcan S',
      make: 'Kawasaki',
      price: 4900,
      year: 2015,
      kilometers: 25000,
      horsepower: 61,
      condition: 'Gebraucht',
    },
    {
      id: 13,
      name: 'Rebel 500',
      make: 'Honda',
      price: 4500,
      year: 2018,
      kilometers: 17000,
      horsepower: 47,
      condition: 'Gebraucht',
    },
    {
      id: 14,
      name: 'Sportster 1200',
      make: 'Harley-Davidson',
      price: 5300,
      year: 2010,
      kilometers: 38000,
      horsepower: 67,
      condition: 'Defekt',
    },
    {
      id: 15,
      name: 'Scout Sixty',
      make: 'Indian',
      price: 7200,
      year: 2019,
      kilometers: 14000,
      horsepower: 78,
      condition: 'Gebraucht',
    },
  ];
}
